# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

reconstruct_caller <- function(input_u, input_v, input_w, max_depth = 1L, max_k = 0L) {
    .Call('_rline_reconstruct_caller', PACKAGE = 'rline', input_u, input_v, input_w, max_depth, max_k)
}

line_caller <- function(input_u, input_v, input_w, binary = 0L, dim = 100L, order = 2L, negative = 5L, samples = 1L, rho = 0.025, threads = 1L) {
    .Call('_rline_line_caller', PACKAGE = 'rline', input_u, input_v, input_w, binary, dim, order, negative, samples, rho, threads)
}

concatenate_caller <- function(input_one, input_two, binary = 0L) {
    .Call('_rline_concatenate_caller', PACKAGE = 'rline', input_one, input_two, binary)
}

